# Imagen base con soporte para Python
FROM python:3.9

# Actualizar pip a la última versión
RUN pip install --no-cache-dir --upgrade pip

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY . /app

# Copiar el archivo requirements.txt al contenedor
COPY requirements.txt /app/requirements.txt

# Instalar las dependencias desde el archivo requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el archivo PDF al directorio adecuado dentro del contenedor
COPY documents/CursosTYC-GIS.pdf /app/documents/CursosTYC-GIS.pdf

# Establecer la codificación del script
ENV PYTHONIOENCODING=utf-8

# Ejecutar el script
CMD [ "python", "script.py" ]
